import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400", // Specify the weight of the font, such as "normal" (400), "bold" (700), etc.
});

export const metadata: Metadata = {
  title: "Syntx Tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} p-4 bg-[#111827] `}>
        {" "}
        <div className="w-full flex flex-col items-center justify-center">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
